version: '2.2'
services:
  app:
    build:
      context: ./
      args:
        - ENVIRONMENT=DEV
    image: nyu-data-repository
    environment:
      - "INVENIO_SEARCH_ELASTIC_HOSTS=['es:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6378/0"
      - "INVENIO_CACHE_TYPE=redis"
  cache:
    image: redis
    restart: "unless-stopped"
    read_only: true
    ports:
      - "6378:6379"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3
    restart: "unless-stopped"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:9200/_cluster/health?wait_for_status=green"]
      interval: 30s
      timeout: 30s
      retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9201:9200"
      - "9301:9300"